# R8 keep rules.
#
# Worth keeping expectations honest: dex is 2.5 MB of a ~99 MB APK, so R8 buys
# a couple of megabytes at most. It is enabled for hygiene and because
# shrinkResources rides along with it — the size problem lives in the native
# libraries, and is solved by shipping one ABI per device, not by shrinking
# bytecode.
#
# Everything below is reached over JNI or by reflection, which R8 cannot see.
# When it strips these the build still succeeds and the app dies at runtime, so
# each rule is deliberate rather than defensive.

# flutter_webrtc: libjingle calls back into these classes from native code.
-keep class org.webrtc.** { *; }
-keep class com.cloudwebrtc.webrtc.** { *; }
-dontwarn org.webrtc.**

# universal_ble and the Android BLE stack, driven through Pigeon-generated
# messengers that are looked up by name.
-keep class com.navideck.universal_ble.** { *; }
-dontwarn com.navideck.universal_ble.**

# ML Kit barcode scanning behind mobile_scanner loads its models reflectively.
-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_barcode.** { *; }
-dontwarn com.google.mlkit.**

# Flutter's own plugin registration is reflective.
-keep class io.flutter.plugins.** { *; }
-keep class io.flutter.embedding.** { *; }

# Keep annotations that the above rely on for their own keep semantics.
-keepattributes *Annotation*, Signature, InnerClasses, EnclosingMethod

# Flutter references Play Core's deferred-component API unconditionally, but
# the library is only on the classpath for apps that actually use dynamic
# feature modules. QuickShare does not, so these references are dead and the
# warnings can be silenced. Generated by R8 itself into
# build/app/outputs/mapping/release/missing_rules.txt.
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.**
-dontwarn com.google.android.play.core.tasks.**
